### PR TITLE
Update bundler version to ~> 2

### PR DESCRIPTION
**Pull request by CAMOBAP795**

### CODE REVIEW

**Comment by ronaldtse** [comment]
The error is with a call to `byebug`, which is purely for debug.

@CAMOBAP795 can you remove that line? It's not supposed to be there.

```
$ bundle exec rake
/home/travis/.rvm/rubies/ruby-2.5.5/bin/ruby -I/home/travis/build/metanorma/iso690render/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.8.2/lib:/home/travis/build/metanorma/iso690render/vendor/bundle/ruby/2.5.0/gems/rspec-support-3.8.2/lib /home/travis/build/metanorma/iso690render/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.8.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
.
[194, 203] in /home/travis/build/metanorma/iso690render/lib/iso690render/render.rb
   194: 
   195:   def self.parse(xml, embedded = false)
   196:     ret = ""
   197:     doc = Nokogiri::XML(xml)
   198:     require "byebug"; byebug
=> 199:     type = type(doc)
   200:     container = doc.at("./bibitem/relation[@type='includedIn']")
   201:     if container && date(doc) && !date(container)
   202:       container.at("./bibitem") << doc.at("./bibitem/date[@type = 'published']").remove
   203:     end
(byebug) 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by CAMOBAP795** [comment]
@ronaldtse done

**Comment by opoudjis** [comment]
This repository is not live, and will be overhauled in light of the metanorma-nist reimplementation. In the very distant future.

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis maybe make sense to go through each repo and deprecate ones which will not be used

**Pull request merged**
